version: '3'

services:
  postgres_db04:
    image: postgres:14-alpine
    container_name: "postgres04"
    environment:
      - "POSTGRES_PASSWORD=314159Po"
      - "POSTGRES_DB=angel_bejaranodb"
      - "POSTGRES_USER=angel_bejarano"
    ports:
      - "10004:5504"
    volumes:
      - "/home/angel_bejarano/postgres:/usr/src/postgres"
    networks:
      - our-library-net
    command: "-p 5504"

  web04:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8004"
    container_name: "django04"
    depends_on: 
      - postgres_db04
    environment:
      PSQL_DBNAME: "angel_bejaranodb"
      PSQL_USERNAME: "angel_bejarano"
      PSQL_PASS: "314159Po"
      PSQL_PASSWORD: "314159Po"
      PSQL_HOST: "postgres_db04"
      PSQL_PORT: "5504"
      JWT_TOKEN_TIME: "120"
    volumes:
      - "/home/angel_bejarano/Project-Rockstar/back:/usr/src/django/music"
    ports:
      - "9004:8004"
    networks:
      - our-library-net
networks:
  our-library-net:
    external: true
    driver: bridge
